### ISSUE TITLE
Auflösung einstellen

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-telekomsport#1]
Wäre es möglich die Auflösung einzustellen. Sehe gerade, dass der FCB.tv-Stream eine Auflösung von 1920x1080 hat, was der FireStick nicht schafft.

Die anderen Livestreams hatten bis jetzt immer "nur" 1280x720.

Danke

**Comment by hubsif** [comment]
Soweit ich das auf die Schnelle sehe, könnte das irgendwie gehen. Aber das muss ich mir genauer ansehen. Dauert vielleicht etwas.

**Comment by hubsif** [comment]
Also, ich hab mir das mal etwas genauer angesehen: Zur Anpassung der Auflösung habe ich leider nichts gefunden. Man kann nur eine maximale Bandbreite bestimmen, die dann aber scheinbar nur die Bitrate des Videos limitiert, nicht aber die Auflösung. Das dürfte also in deinem Fall nichts bringen. Sorry.

**Comment by MRLB** [comment]
Hhm. Schade. Vielleicht hilft es ja auch, wenn man die Bandbreite bisschen runtersetzen kann und die Auflösung beibehält. (Wäre auch eine top-Einstelloption wenn man mal wieder mobil schaut) und Datenvolumen sparen will/muss). Aber so lange es nur fcb.tv ist kann ich damit leben. 
Wäre es viel Aufwand die Einstelloption noch mit einzubauen?
