### ISSUE TITLE
BBL - Aktuelles On Demand wird nicht angeboten

### ISSUE THREAD

**Issue by chessplayer60** [hubsif/kodi-telekomsport#12]
Hallo Hubsif,

erst mal, wie immer, vielen Dank für die Zeit, die Du in das Projekt steckst. Ich wollte Dich auf folgendes Problem aufmerksam machen:
Wenn ich heute (29.10.) die Partien von gestern anschauen oder deren Game-Report sehen möchte, dann kann ich das auf der TelekomSport-Website unter der Rubrik "OnDemand" tun. In Deinem Plugin jedoch ist das nirgends zu finden. OnDemand gibt es lediglich nach Wochen geordnet, aber es endet mit dem Sonntag der letzten Woche.

Wäre es nicht ggf. sinnvoller, das Menü der Struktur auf der Website anzupassen und zunächst mal nach Live und OnDemand zu unterteilen und anschließend in die Kategorien zu gehen? Oder aber nach den Kategorien Live und OnDenamd zu nehmen und danach dann zeitlich zu ordnen?

Cheers,

chessplayer

**Comment by chessplayer60** [comment]
Ich muss das etwas revidieren: ein paar Stunden später gab es dann auch "Woche 5 - Kürzlich hinzugefügt", aber eben deutlich später als über die Website ...

**Comment by hubsif** [comment]
Hi! Hm, das wundert mich etwas, da das Plugin eigentlich die gleichen Inhalte abruft wie die Webseite. ...aber halt nur eigentlich, die Unterschiede scheinen sich hier wohl bemerkbar gemacht zu haben.
Zumindest sollten die gleichen Inhalte wie in der App angezeigt werden, deshalb hoffe ich, dass es einigermaßen vollständig bleibt.

Ich schließe das hier dann mal...
