### ISSUE TITLE
FCB.tv Livestream

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-telekomsport#14]
Leider wird bei FCB.tv nur noch das Programm angezeigt und es besteht keine Möglichkeit das 24/7-Programm zu starten.

**Comment by hubsif** [comment]
Besser spät als nie:
Das hat die Telekom scheinbar abgeschafft: Sowohl auf der Webseite als auch in der App sehe ich keinen 24/7-Stream mehr.
