### ISSUE TITLE
Wiederholungen nicht abspielbar auf China-Box (Amlogic S905X) mit Leia-Build

### ISSUE THREAD

**Issue by chessplayer60** [hubsif/kodi-telekomsport#15]
Hallo hubsif,
zunächst mal funktioniert Dein Plugin einwandfrei auf meiner Nvidia Shield (also Android TV) sowie mit dem Standard-LibreELEC (8.2.1) auf RPi3 und Wetek-Play und ebenso auf den [hier verlinkten](https://forum.libreelec.tv/thread/9319-8-2-1-1-libreelec-8-2-for-s905-s905x/) Images für Amlogic S905X.

Möchte man diese Boxen allerdings voll mit LibreELEC nutzen, dann braucht man eher [diesen Build](https://forum.libreelec.tv/thread/10301-9-0-libreelec-9-x-for-s905-s905x), also LibreELEC 9 mit Kodi Leia.

Dabei ist es dann so, dass ich zwar Gamereports der BBL abspielen kann (per Auswahl und dann "OK" auf der FB), aber keine Wiederholungen. Nur "OK" bleibt folgenlos und langer Druck auf "OK" gibt einem nur die Option "Zu Favoriten hinzufügen" (beim Gamereport kommt dann auch "Wiedergeben" und "Ab hier abspielen").

Ich habe mal [hier](http://sprunge.us/DiEU) ein Log  gepostet, wo ich zunächst einen Gamereport gestartet und gleich wieder beendet habe und anschließend versucht habe, die Wiederholung anzuschauen, was nicht ging.

Ich weiß nun nicht, ob das für Dich schon ein Thema ist, würde mich aber sehr freuen, wenn es das wäre, damit ich meinem Sohn zu Weihnachten eine voll funktionsfähige Box schenken kann ...

Falls ich noch weitere Infos liefern kann, dann lass es mich bitte wissen. Ansonsten: danke für dein tolles Plugin!

chessplayer

**Comment by hubsif** [comment]
Hallo chessplayer,

Entschuldige die späte Antwort. Frage vorweg: Ist das Problem noch vorhanden?

Ich hab mir dein Log mal angekuckt, doch leider kann ich daraus nicht erkennen, warum er nicht abspielt. Eigentlich werden Gamereports und Wiederholungen auf die gleiche Art gestartet.
Vielleicht liegts an Kodi 18 Leia. Damit hab ich noch nicht getestet. Vielleicht komm ich bald mal dazu, das zu tun.

**Comment by hubsif** [comment]
Hm, da fällt mir ein, dass es doch einen entscheidenen Unterschied zwischen Gamereports und Wiederholungen gibt: Wiederholungen sind nicht frei, möglicherweise funktioniert also was mit der Authentifizierung nicht...

**Comment by chessplayer60** [comment]
Hallo hubsif,

das Problem besteht weiter, aber ich glaube eher, das es liegt am Alphastadium des Leia-Builds (oder aber wirklich an einem Kompatibilitätsproblem). Habe gestern nämlich mal einen Gamereport vollständig angeschaut und danach wurde die Wiederholung einfach automatisch abgespielt. Somit ist es also nicht so, dass das nicht abgespielt werden kann, es kann nur nicht auf die übliche Art ausgewählt werden.
Ist das mal angespielt worden, dann kann man es hinterher auch normal durch Klick auf das dann ja mit dem "teilweise abgespielt"-Symbol versehehen Eintrag wieder starten ...

Es gibt seit gestern auch ein neues Release des Builds - damit muss ich das dann mal testen. Es kann aber natürlich auch sein, dass sich in der Kodi-API etwas geändert hat von Krypton auf Leia, aber das weiß ich nicht. In dem Fall hättest Du wohl spätestens dann wieder zu tun, wenn Leia Standard wird ...

Danke jedenfalls für Dein Engagement!

**Comment by hubsif** [comment]
Hallo chessplayer,

Ich habe jetzt auch zufällig eine dieser "China-Boxen", ebenfalls genau mit Amlogic S905X Chip. 
Du hattest geschrieben:
> Möchte man diese Boxen allerdings voll mit LibreELEC nutzen

Ich hab auf meiner LibreELEC 8 laufen und bisher nichts vermisst. Kannst du mir kurz sagen, was du mit "voll nutzen" gemeint hast?

**Comment by chessplayer60** [comment]
Hallo hubsif, in der Tat funktioniert Dein Plugin ja mit den Krypton-Builds. Allerdings kann man mit diesen weder Amazon Prime noch Netflix nutzen (Sky Go geht). Das meinte ich mit "voll nutzen", wobei das für mich persönlich kein Problem ist, da ich Netflix und Amazon per Smart-TV-App direkt nutze. Für meinen bereits auswärtig wohnenden Sohn sieht das allerdings anders aus ...

**Comment by hubsif** [comment]
So, ich hatte endlich mal etwas Zeit und hoffe einfach mal, dass es sich hier um die gleiche Ursache gehandelt hat, wie in #18 und die Probleme mit Kodi 18 in v1.2.2 behoben sind (zumindest geht es bei mir jetzt).
Wenn nicht, bitte das Issue wieder aufmachen.
