### ISSUE TITLE
Basketball - Kürzlich hinzugefügt unvollständig

### ISSUE THREAD

**Issue by dspyrhsu** [hubsif/kodi-telekomsport#16]
Hallo hubsif,

bei der easycredit bbl wollte ich gerade den Gamereport des Ludwigsburger Spiels von gestern Abend schauen, aber keines der gestrigen Spiele wird heute, am Sonntag, den 17.12., unter "Woche 11 - Kürzlich hinzugefügt" angezeigt. Im Webbrowser unter telekomsport.de sind sie vorhanden.

Stimmt da was mit dem Webscraping nicht?

Ansonsten möchte ich mich vor allem sehr bedanken, dass Du dieses Addon zur Verfügung stellst!

Reinhold

**Comment by hubsif** [comment]
Hallo Reinhold,

Vielen Dank für dein Feedback.
Wegen dem Ludwigsburger Spiel: Ich hatte am Sonntag gleich mal gekuckt. Das Problem war, dass das Spiel einfach nicht (für die App) zur Verfügung gestellt wurde.
Das Addon ruft die Daten über die gleiche Schnittstelle ab, wie die App. In der App war das Spiel auch nicht verfügbar. Mittlerweile wurde das wohl korrigiert. Es war also letztlich kein Problem des Addons, sondern der Telekom/ihres Diensteanbieters.

Warum das Spiel allerdings über die Webseite verfügbar war, verstehe ich noch nicht so ganz, denn ich dachte auch die Webseite bekommt ihre Inhalte letztlich über die gleiche Schnittstelle. Das scheint wohl doch nicht so ganz der Fall zu sein...

**Comment by dspyrhsu** [comment]
Ok, die App hatte ich nicht ausprobiert. Aber dass die Telekom gerade die Apps doch eher stiefmütterlich behandelt, das hat man insbesondere an der Fire-TV-App für Telekom Basketball gemerkt, die ja nie aktualisiert wurde ...
