### ISSUE TITLE
[BBL] Gamereports do not work

### ISSUE THREAD

**Issue by mighty0n3** [hubsif/kodi-telekomsport#18]
Servus,

vorab erstmal danke für das durchaus gelungene Addon ;)

Kann es eventuell sein, dass unter den Alpha/Betas von Leia die Gamereports von den BBL-Spielen nicht funktionieren? Wiederholungen gehen ohne Probleme

Ich weiß, alpha builds und so aber das ist leider der einzige Weg Amazon VOD zu nutzen .. ;-)

**Comment by hubsif** [comment]
Hallo mighty0n3,

> Kann es eventuell sein, dass unter den Alpha/Betas von Leia die Gamereports von den BBL-Spielen nicht funktionieren?

Das könnte sein, mit Leia habe ich noch nicht getestet. Und in #15 hat ein User auch schon beklagt, dass etwas mit Leia nicht funktioniert. (Ich dachte erst, es würde sich vielleicht um das selbe Problem handeln, aber bei ihm ist es wohl umgekehrt: Er kann Gamereports abspielen, aber keine Wiederholungen. :astonished:)

Mittlerweile gibt es wohl auch eine neue API der Telekom, das Plugin müsste wohl also grundsätzlich mal erneuert werden, auch für Leia. Ich bin allerdings noch nicht dazu gekommen, vielleicht wird das nach Ostern besser... :wink:

**Comment by mighty0n3** [comment]
Alles klar - kein Stress ;) 
Vielen Dank für die Zeit und Arbeit die du da reinsteckst :)

**Comment by MRLB** [comment]
Am Freitag beginnt die neue 3. Liga-Saison. Schon klar, ob es eine neue API gibt?

**Comment by hubsif** [comment]
Hi. Ja, es gibt wohl eine neue API. Wie man allerdings an meiner verzögerten Reaktion merkt, habe ich gerade wenig Zeit dazu. Kann nicht genau sagen, wann ich zu einem Update komme...

**Comment by MRLB** [comment]
3. Liga läuft 1a

**Comment by MRLB** [comment]
Zumindest live

**Comment by hubsif** [comment]
So, also das Problem mit Kodi 18 Leia hat User @egolus wohl schon länger erkannt und in seinem Fork gefixt. Ohne weiteren Kommentar und eigenen Test mit Kodi 18 wußte ich aber nicht, was dahinter steckt.
Mit der neuen Version v1.2.2 sollten die Videos jetzt auch unter Kodi 18 abspielen. Außerdem hab ich die von @MRLB vorgeschlagene Verwendung des Inputstream eingepflegt, die bei mir allerdings keine erkennbare Verbesserung brachte.

**Comment by egolus** [comment]
Ich hatte gar nicht mehr auf dem Schirm, dass ich diese Änderung auf Github hatte. Ich hatte es beim testen eingefügt und vergessen. 

Nächstes mal mache ich einen PR auf
