### ISSUE TITLE
HBL geht nicht

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-telekomsport#2]
Eigentlich sollte seit 18:30h der HBL-Supercup übertragen werden. Leider findet sich im HBL-Ordner zurzeit nichts

**Comment by hubsif** [comment]
Danke für das Feedback!

Stimmt, der HBL-Ordner ist leer, weil der "Pixum Supercup" von der Telekom-API in keiner der Kategorien geführt wird. Das Spiel wurde aber als Live-Game in der Hauptseite geladen.
Allerdings konnte man es darüber auch nicht ansehen, weil dieser Event keinen Titel hat und beim Auswählen das Addon deshalb in einen Fehler lief.

Schau mal, ob's mit dem neuen [Release v1.0.1](https://github.com/hubsif/kodi-telekomsport/releases/tag/v1.0.1) wie gewünscht funktioniert.

**Comment by MRLB** [comment]
Danke. Der Supercup ist leider schon vorbei. Am Donnerstag beginnt die richtige Liga in der HBL. Dann sollten die Spiele ja demnächst im HBL-Ordner auftauchen. Donnerstag wieder testen.

**Comment by MRLB** [comment]
Der HBL-Ordner ist zwar immer noch leer, aber unter Jetzt live sind beide HBL-Spiele abrufbar. Leider gibt es keine Info, auf welchem Stream welche Partie läuft. Es steht nur "DKB HBL ..." dort. Stefans sind wie erwartet 1280x720.

**Comment by hubsif** [comment]
Mit "HBL-Ordner" meinst du schon den "Sky Sport Kompakt - DKB Handball-Bundesliga", oder?
Da gibt es bei mir "LIVE" und "Kürzlich hinzugefügt" und unter "LIVE" war bis gerade auch noch das Spiel (das auch im Hauptmenü unter "jetzt live" war)...
Vielleicht wurde das seitens der Telekom erst während des Spiels angepasst?

**Comment by MRLB** [comment]
Ja. Gibt's bei mir jetzt auch. Und unter live fehlen leider die Spielpaarungen. Aber auch das wird ein Telekom-Problrm sein

**Comment by kakaiser** [comment]
Vlcht mal zum Vergleich wie es im Addon dargestellt ist

Fussball - 3. Liga => Live:     SC Paderborn 07 - SV Meppen (3. Liga -
Spieltag 6)
Sky Sport Kompakt => Live:    DKB Handball Bundesliga (DKB Handball
Bundesliga - Spieltag 1)

Hast du Visibility ob in der API für Sky Kompakt die Spielpaarung vllcht in
einem anderen Feld hinterlegt ist?

Bei kürzlich hinzugefügt sieht es genauso aus - zeigt allerdings das
richtige Bild an mit der Spielpaarung. Vlcht wäre das auch ein Umweg das
darzustellen? Sprich das Bild mit anzuzeigen?

Sky CL können wir ja noch nicht testen - aber könnte sein das das dann
ebenfalls dort so auftaucht.

Grüsse Karsten





2017-08-24 21:12 GMT+02:00 MRLB <notifications@github.com>:

**Comment by hubsif** [comment]
Ja stimmt, das wird nicht schön angezeigt. Das liegt daran, dass die Daten in dem Fall anders aufgebaut sind. Werd das fürs nächste Release umbauen und hoffentlich wird das dann für BL & Co genauso ausgeliefert...

**Comment by MRLB** [comment]
Die relive-Streams bei der HBL gehen leider noch nicht. Oder gibt es dort keine restreams?

**Comment by kakaiser** [comment]
Haben bei mir getan. Aufgeteilt auf zwei Halbzeiten

Am 27.08.2017 19:55 schrieb "MRLB" <notifications@github.com>:

**Comment by MRLB** [comment]
Echt? Wenn ich auf Lemgo - Löwen Klick kommt bei mir keine weitere Auswahlmöglichkeit. Bei der Bundesliga genauso. Dort sind zwar die Einzelpartien aufgelistet, ein Video kann ich aber nicht starten (unter kürzlich hinzugefügt). bei den Direkten Telekom-Sachen klappt alles.

**Comment by kakaiser** [comment]
Version 1.0.3? Oder welche Version hast du drauf?

Am 27.08.2017 20:28 schrieb "MRLB" <notifications@github.com>:

**Comment by MRLB** [comment]
Oh. Hab noch 1.0.2. Ich update gleich und schau nochmal :-)

**Comment by MRLB** [comment]
Mit 1.0.3 geht's. Sorry. Mein Fehler. Danke :-)
