### ISSUE TITLE
Update aus ZIP installieren FEHLGESCHLAGEN

### ISSUE THREAD

**Issue by Eckbert42** [hubsif/kodi-telekomsport#22]
Hi,

habe gerade versucht das Update zu installieren. Hab dann eine Fehlermeldung bekommen.
Im Log-file steht folgendes:

21:38:45.203 T:1807737776   ERROR: GetDirectory - Error getting
21:38:48.372 T:1807737776   ERROR: Previous line repeats 2 times.
21:38:48.372 T:1807737776 WARNING: COMXImageFile::GetCodingType progressive images not supported by decoder
21:38:48.372 T:1807737776 WARNING: Previous line repeats 1 times.
21:38:48.372 T:1807737776  NOTICE: LoadJpeg: unable to load /home/pi/.kodi/addons/plugin.video.youtube/fanart.jpg

**Comment by Eckbert42** [comment]
Bei Kodi kommt oben rechts eine Fehlermeldung:
Installation des Addons aus ZIP-Datei fehlgeschlagen. Die Datei hat nicht...

Mehr zeigt das Pop-Up nicht an.

**Comment by MRLB** [comment]
Bei mir hat's gestern problemlos geklappt. Habe aber die id von magentasport zurück auf telekomsport geändert, damit das alte Addon überschrieben wird

**Comment by Eckbert42** [comment]
Habe auch versucht, das TelekomSport Addon zu deinstallieren und anschließend MagentaSport zu installieren. Ging leider auch nicht.
Ein erneutes installieren des TelekomSport Addons ging wieder problemlos.

**Comment by Eckbert42** [comment]
Vielen Dank! Es hat funktioniert!
