### ISSUE TITLE
Fire TV geht nicht

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-telekomsport#3]
Wollte gerade das Basketball EM-Spiel via FireTV schauen. Leider kommt folgende Fehlermeldung. Auf einem Android-Tablet läuft es aber problemlos:

(Den Link hab ich gekürzt)

VOD-Sachen funktionieren problemlos

`15:03:27.516 T:1109002408  NOTICE: Trying to open: 44100 samplerate 12 channelMask 4 encoding

15:03:27.528 T:1109002408  NOTICE: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 42336 m_frames: 2646 m_frameSize: 8 channels: 2

15:03:27.846 T:1108910816 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F11047

15:03:27.847 T:1108910816   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F11047

15:03:31.928 T:1106434920  NOTICE: VideoPlayer: Opening: https://universallivebbl-lh.akamaihd.net/i...

15:03:31.928 T:1106434920 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED

15:03:32.470 T:1396421128  NOTICE: Creating InputStream

15:03:32.896 T:1396421128  NOTICE: Creating Demuxer

15:04:03.194 T:1396421128   ERROR: OpenDemuxStream - Error creating demuxer

15:04:03.194 T:1396421128  NOTICE: CVideoPlayer::OnExit()

15:04:03.203 T:1106434920   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F11047]

15:04:03.207 T:1106434920  NOTICE: CVideoPlayer::CloseFile()

15:04:03.207 T:1106434920  NOTICE: VideoPlayer: waiting for threads to exit

15:04:03.208 T:1106434920  NOTICE: VideoPlayer: finished waiting

15:04:03.208 T:1106434920  NOTICE: CVideoPlayer::CloseFile()

15:04:03.208 T:1106434920  NOTICE: VideoPlayer: waiting for threads to exit

15:04:03.208 T:1106434920  NOTICE: VideoPlayer: finished waiting

15:04:06.172 T:1613708896 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F11047

15:04:06.172 T:1613708896   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F11047
`

**Comment by MRLB** [comment]
Kodi 17.4 auf beiden Geräten.

**Comment by MRLB** [comment]
So. Mit 17.3 geht FCB.tv problemlos auf FireTV. Scheint ein Problem nur mit 17.4 zu geben.

**Comment by MRLB** [comment]
Hhm. nachdem ich kurz ein VOD-Video angeschaut habe geht nun auch der Livestream via FireTV

**Comment by hubsif** [comment]
Geht's denn mittlerweile verlässlicher? Sieht mir eher nach einem Telekom Server oder Kodi Problem aus...

**Comment by MRLB** [comment]
Auf FireStick ist es Glücksache. Auf FireTV 2 in der Regel na

**Comment by MRLB** [comment]
Ja, statt na

**Comment by MRLB** [comment]
Ich glaube das liegt an der zu hohen Datenrate für die Geräte. Ich hab ein wenig die Bandbreite runtergedreht und auf einmal ging es nicht mehr. Möglich die Bandbreite zu regulieren?
