### ISSUE TITLE
Login Daten

### ISSUE THREAD

**Issue by Eckbert42** [hubsif/kodi-telekomsport#4]
Ich schaue gerade die Eurobasket.
Läuft einwandfrei. Macht richtig Spaß.

Ich frage mich nur, wie und wo ich meine Login-Daten eingeben kann für die Angebote, die nicht frei sind.
Bei dem TelekomBasketball Addon gab es das.

**Comment by chessplayer60** [comment]
Erst mal ein großer Dank an HubSif für die erneute Arbeit. Dann möchte ich mich Eckbert42 gerne in allem anschließen. Es gibt keine Konfigurierungsmöglichkeit bei diesem Addon.

**Comment by hubsif** [comment]
Login ist in Arbeit. Ist nur etwas aufwendiger, da ja jetzt nach Buchungspaketen unterschieden werden muss...

**Comment by chessplayer60** [comment]
Super, danke! Mir reicht ja Basketball ... ;-)

**Comment by Eckbert42** [comment]
Jetzt bin ich gerade etwas verwundert.
Habe gerade über das Addon ein DEL Livestream gestartet.
Der Stream läuft, obwohl dies kein kostenfreier Stream ist.
Ich habe das DEL Paket zwar auch gebucht, aber woher weis das Addon dies, ohne meine Login-Daten ?

**Comment by Eckbert42** [comment]
Jetzt wirds noch verrückter.
Sogar der Live-Stream für die 3. Liga funktioniert.
Dieses Paket hab ich aber wirklich nicht gebucht.
Hab das Ganze mal am Browser über den PC gegengeprüft...der sagt mir ganz klar, dass ich die Streams ohne Abo nicht schauen kann.
