### ISSUE TITLE
Wrong category names

### ISSUE THREAD

**Issue by egolus** [hubsif/kodi-telekomsport#5]
A lot of categories are shown as "Without Name" / "Ohne Namen"

for example under "Eishockey - DEL":
![screenshot000](https://user-images.githubusercontent.com/6723020/30804624-66a765cc-a1ee-11e7-96b9-6eea6e0aa243.png)

**Comment by hubsif** [comment]
Thanks for reporting. At the time I created this part, there wasn't enough server side content for me to understand how it's structured. Should be ok with the latest release now.

**Comment by egolus** [comment]
Thanks for the quick response. This looks good
