### ISSUE TITLE
Video on demand funktioniert nicht mehr

### ISSUE THREAD

**Issue by kgraefe** [hubsif/kodi-telekomsport#8]
Ich versuche, die Spielzusammenfassungen der DEL zu schauen. Dabei erscheint die Fehlermeldung "Mindestens eine Datei konnte nicht abgespielt werden" statt des Menüs, wo man auswählen konnte, ob man die Zusammenfassung oder das komplette Spiel nochmal anschauen möchte.

Aufgefallen ist mir auch, dass die Spiele jetzt nach Wochen statt (wie immer noch auf der Webseite) nach Spieltagen kategorisiert sind. Das stört mich zwar nicht , aber vielleicht hat es etwas damit zu tun?

Kodi läuft bei mir auf einem Amazon FireTV Stick (Android).

Anbei noch das (etwas gekürzte) [Log File](https://github.com/hubsif/kodi-telekomsport/files/1388765/kodi.log).

**Comment by hubsif** [comment]
Hallo Konrad,

Danke für den Hinweis. Ich hab was gefunden, ich hoffe es ist mit dem neuen Release 1.2.1 behoben. Schau mal, ob es bei dir funktioniert.

**Comment by kedvsk** [comment]
Gleiches (oder ähnliches) Problem unter Kodi auf Android und Raspberry PI. Wo kann die neue Version herunterladen?

20:59:49.909 T:530809128016 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F13344
20:59:49.909 T:530809128016   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F13344

**Comment by kgraefe** [comment]
Funktioniert. Danke. :-)

**Comment by kgraefe** [comment]
@kedvsk https://github.com/hubsif/kodi-telekomsport/releases

**Comment by kedvsk** [comment]
Sorry, hatte ich inzwischen gefunden. Funktioniert - ja, aber ich erhalte nach wie vor folgende Fehlermeldungen:

Windows:
22:13:04.317 T:1520 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?isLivestream=False&isPay=False&mode=video&videoid=33153
22:13:04.317 T:1520   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?isLivestream=False&isPay=False&mode=video&videoid=33153
22:13:04.320 T:1520 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?isLivestream=False&isPay=True&mode=video&videoid=33118
22:13:04.320 T:1520   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?isLivestream=False&isPay=True&mode=video&videoid=33118
22:13:31.774 T:1028   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?isLivestream=False&isPay=True&mode=video&videoid=33118]
22:13:39.638 T:1028  NOTICE: VideoPlayer: Opening: https://tsstv-vh.akamaihd.net/i/p-2780_u-_l-_a-_c-DE_e-33118_i-2093883020171017201340_k-_q-_t-hdvideo/hdflash/bbl/2017/fullmatch/171015_ulm_got_rl_,192,450,850,1500,3000,.mp4.csmil/master.m3u8?hdnea=exp=1508271520~acl=*~hmac=4ea7acdf5c7c3c2bcde941a2fa57a9a3408d8dccc6e100855ee92ec5e99f1921

Raspberry PI:
21:46:15.897 T:1493169056 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?isLivestream=False&isPay=False&mode=video&videoid=33153
21:46:15.897 T:1493169056   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?isLivestream=False&isPay=False&mode=video&videoid=33153
21:46:15.914 T:1394602912 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?isLivestream=False&isPay=True&mode=video&videoid=33118
21:46:15.915 T:1394602912   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?isLivestream=False&isPay=True&mode=video&videoid=33118
21:46:21.126 T:1961947136  NOTICE: VideoPlayer: Opening: https://tsstv-vh.akamaihd.net/i/p-2780_u-_l-_a-_c-DE_e-33118_i-7158997020171017194620_k-_q-_t-hdvideo/hdflash/bbl/2017/fullmatch/171015_ulm_got_rl_,192,450,850,1500,3000,.mp4.csmil/master.m3u8?hdnea=exp=1508269880~acl=*~hmac=eab38ea03708263249a1907bd18e793b783ecb85245514301e0d5b12e356bc96
...
21:46:31.686 T:1493169056 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?isLivestream=False&isPay=False&mode=video&videoid=33153
21:46:31.686 T:1493169056   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?isLivestream=False&isPay=False&mode=video&videoid=33153
21:46:31.696 T:1493169056 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?isLivestream=False&isPay=True&mode=video&videoid=33118
21:46:31.696 T:1493169056   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?isLivestream=False&isPay=True&mode=video&videoid=33118

Es scheint auch so, als ob die Meldung "Mindestens ein Stream konnte nicht abgespielt werden" aufblitzt. Es kam auch vor, dass erst der zweite Versuch einen Stream zu starten erfolgreich war.

**Comment by hubsif** [comment]
Hallo @kedvsk ,

> Funktioniert - ja, aber ich erhalte nach wie vor folgende Fehlermeldungen:

Heißt das, dass die Streams abgespielt werden? Wenn ja, dann würde ich die Errors einfach mal ignorieren ;).

**Comment by kedvsk** [comment]
Ein Stream wird dann nicht abgespielt, wenn ein Stream bereits läuft, dieser beendet wird un ein neuer gestartet wird.
Auszug des Logfiles (Windows 10):

19:01:12.980 T:4668  NOTICE: CVideoPlayer::CloseFile()
19:01:12.980 T:4668  NOTICE: VideoPlayer: waiting for threads to exit
19:01:12.991 T:1440  NOTICE: CVideoPlayer::OnExit()
19:01:12.991 T:1440  NOTICE: Closing stream player 1
19:01:12.991 T:1440  NOTICE: Waiting for audio thread to exit
19:01:13.022 T:4368  NOTICE: thread end: CVideoPlayerAudio::OnExit()
19:01:13.022 T:1440  NOTICE: Closing audio device
19:01:13.037 T:1440  NOTICE: Deleting audio codec
19:01:13.037 T:1440  NOTICE: Closing stream player 2
19:01:13.037 T:1440  NOTICE: waiting for video thread to exit
19:01:13.066 T:4776  NOTICE: thread end: video_thread
19:01:13.066 T:1440  NOTICE: deleting video codec
19:01:13.069 T:1440  NOTICE: DXVA::CDecoder::Close - closing decoder
19:01:13.069 T:1440  NOTICE: DXVA::Close - closing decoder context
19:01:13.072 T:4668  NOTICE: VideoPlayer: finished waiting
19:01:13.083 T:4668   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
19:01:13.092 T:4668  NOTICE: CVideoPlayer::CloseFile()
19:01:13.092 T:4668  NOTICE: VideoPlayer: waiting for threads to exit
19:01:13.092 T:4668  NOTICE: VideoPlayer: finished waiting
19:01:13.092 T:4668  NOTICE: CVideoPlayer::CloseFile()
19:01:13.092 T:4668  NOTICE: VideoPlayer: waiting for threads to exit
19:01:13.092 T:4668  NOTICE: VideoPlayer: finished waiting
19:01:13.649 T:5228 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221
19:01:13.649 T:5228   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221
19:01:13.935 T:5228 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221
19:01:13.935 T:5228   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221
19:01:16.118 T:4668   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221]
19:01:17.914 T:4668  NOTICE: VideoPlayer: Opening: https://universallivebbl-lh.akamaihd.net/i/p-2780_u-_l-_a-_c-DE_e-20391_i-3440798720171022170117_k-_q-_t-hdvideo/telekombasketball08_1@42869/master.m3u8?hdnea=exp=1508691977~acl=*~hmac=9dc69990150c83a58335f7b933f0a20d88b9a466781d1415fe4df2e1c4b2b483
19:01:17.914 T:4668 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:01:18.150 T:592  NOTICE: Creating InputStream
19:01:18.268 T:592  NOTICE: Creating Demuxer
19:01:27.347 T:592  NOTICE: Opening stream: 24 source: 256
19:01:27.347 T:592  NOTICE: Creating video codec with codec id: 28
19:01:27.347 T:592  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
19:01:27.348 T:592  NOTICE: Creating video thread
19:01:27.348 T:592  NOTICE: Opening stream: 25 source: 256
19:01:27.348 T:592  NOTICE: Finding audio codec for: 86018
19:01:27.348 T:5816  NOTICE: running thread: video_thread
19:01:27.348 T:592  NOTICE: Creating audio thread
19:01:27.348 T:2488  NOTICE: running thread: CVideoPlayerAudio::Process()
19:01:27.350 T:5816  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
19:01:27.353 T:5816   ERROR: CDVDVideoCodecFFmpeg::Decode - avcodec_decode_video returned failure
19:01:27.360 T:2488   ERROR: Previous line repeats 28 times.
19:01:27.360 T:2488  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
19:01:27.371 T:5816   ERROR: CDVDVideoCodecFFmpeg::Decode - avcodec_decode_video returned failure
19:01:27.388 T:4668   ERROR: Previous line repeats 19 times.
19:01:27.388 T:4668  NOTICE: CVideoPlayer::CloseFile()
19:01:27.388 T:4668  NOTICE: VideoPlayer: waiting for threads to exit
19:01:27.389 T:592  NOTICE: CVideoPlayer::OnExit()
19:01:27.389 T:592  NOTICE: Closing stream player 1
19:01:27.389 T:592  NOTICE: Waiting for audio thread to exit
19:01:27.389 T:2488   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
19:01:27.389 T:2488  NOTICE: thread end: CVideoPlayerAudio::OnExit()
19:01:27.389 T:592  NOTICE: Closing audio device
19:01:27.451 T:592  NOTICE: Deleting audio codec
19:01:27.452 T:592  NOTICE: Closing stream player 2
19:01:27.452 T:592  NOTICE: waiting for video thread to exit
19:01:28.388 T:5816 WARNING: CRenderManager::Configure - timeout waiting for configure
19:01:28.388 T:5816   ERROR: CVideoPlayerVideo::OutputPicture - failed to configure renderer
19:01:28.388 T:5816  NOTICE: thread end: video_thread
19:01:28.388 T:592  NOTICE: deleting video codec
19:01:28.394 T:592  NOTICE: DXVA::CDecoder::Close - closing decoder
19:01:28.394 T:592  NOTICE: DXVA::Close - closing decoder context
19:01:28.416 T:4668  NOTICE: VideoPlayer: finished waiting
19:01:28.416 T:4668  NOTICE: CVideoPlayer::CloseFile()
19:01:28.416 T:4668  NOTICE: VideoPlayer: waiting for threads to exit
19:01:28.417 T:4668  NOTICE: VideoPlayer: finished waiting
19:01:31.978 T:4668   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221]
19:01:31.987 T:5696 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221
19:01:31.987 T:5696   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10221
19:01:33.644 T:4668  NOTICE: VideoPlayer: Opening: https://universallivebbl-lh.akamaihd.net/i/p-2780_u-_l-_a-_c-DE_e-20391_i-9968667720171022170133_k-_q-_t-hdvideo/telekombasketball08_1@42869/master.m3u8?hdnea=exp=1508691993~acl=*~hmac=79f52995b404e199653f5679af863e66207d0e00e484d4c138d3b69a958e5e49
19:01:33.644 T:4668 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:01:33.880 T:1516  NOTICE: Creating InputStream
19:01:33.902 T:1516  NOTICE: Creating Demuxer
19:01:42.631 T:1516  NOTICE: Opening stream: 24 source: 256
19:01:42.631 T:1516  NOTICE: Creating video codec with codec id: 28
19:01:42.631 T:1516  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
19:01:42.631 T:1516  NOTICE: Creating video thread
19:01:42.631 T:1516  NOTICE: Opening stream: 25 source: 256
19:01:42.631 T:1516  NOTICE: Finding audio codec for: 86018
19:01:42.632 T:1516  NOTICE: Creating audio thread
19:01:42.633 T:5800  NOTICE: running thread: video_thread
19:01:42.633 T:5804  NOTICE: running thread: CVideoPlayerAudio::Process()
19:01:42.633 T:5800  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
19:01:42.643 T:5804  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
19:01:42.646 T:5800   ERROR: CDVDVideoCodecFFmpeg::Decode - avcodec_decode_video returned failure
19:01:42.679 T:4668   ERROR: Previous line repeats 48 times.
19:01:42.679 T:4668  NOTICE: D3D: rendering method forced to DXVA processor
19:01:42.679 T:4668  NOTICE: DXVA::CProcessorHD::InitProcessor: Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:yes.
19:01:42.684 T:4668 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
19:01:43.201 T:5800 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
19:01:44.264 T:5800 WARNING: Previous line repeats 2 times.
19:01:44.264 T:5800  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 40000
19:01:44.768 T:5800 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

Der nächste Versuch funktioniert dann wieder.

Logfile (LibreElec):

14:51:01.058 T:1961689088   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
14:51:08.706 T:1449128864 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10215
14:51:08.706 T:1449128864   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10215
14:51:08.715 T:1267725216 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218
14:51:08.715 T:1267725216   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218
14:51:11.539 T:1961689088   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10215]
14:51:14.292 T:1961689088  NOTICE: VideoPlayer: Opening: https://universallivebbl-lh.akamaihd.net/i/p-2780_u-_l-_a-_c-DE_e-20385_i-4450288420171022125113_k-_q-_t-hdvideo/telekombasketball06_1@42867/master.m3u8?hdnea=exp=1508676973~acl=*~hmac=a905b8b2cf38ab29cb75fa486d2dc5b037aed034c3489b4748d759a7a4e1a4e6
14:51:14.292 T:1961689088 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:51:14.552 T:1329591200  NOTICE: Creating InputStream
14:51:14.841 T:1329591200  NOTICE: Creating Demuxer
14:51:23.811 T:1329591200  NOTICE: Opening stream: 12 source: 256
14:51:23.811 T:1329591200  NOTICE: Creating video codec with codec id: 28
14:51:23.823 T:1329591200  NOTICE: Creating video thread
14:51:23.823 T:1329591200  NOTICE: Opening stream: 13 source: 256
14:51:23.823 T:1133507488  NOTICE: running thread: video_thread
14:51:23.823 T:1329591200  NOTICE: Finding audio codec for: 86018
14:51:23.826 T:1329591200  NOTICE: Creating audio thread
14:51:23.826 T:1125118880  NOTICE: running thread: CVideoPlayerAudio::Process()
14:51:23.841 T:1125118880  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
14:51:24.855 T:1133507488 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
16:47:58.497 T:1961689088 WARNING: Previous line repeats 3 times.
16:47:58.498 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:47:58.498 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:47:58.498 T:1329591200  NOTICE: CVideoPlayer::OnExit()
16:47:58.498 T:1329591200  NOTICE: Closing stream player 1
16:47:58.498 T:1329591200  NOTICE: Waiting for audio thread to exit
16:47:58.541 T:1125118880  NOTICE: thread end: CVideoPlayerAudio::OnExit()
16:47:58.541 T:1329591200  NOTICE: Closing audio device
16:47:58.593 T:1329591200  NOTICE: Deleting audio codec
16:47:58.594 T:1329591200  NOTICE: Closing stream player 2
16:47:58.594 T:1329591200  NOTICE: waiting for video thread to exit
16:47:58.597 T:1133507488  NOTICE: thread end: video_thread
16:47:58.599 T:1329591200  NOTICE: deleting video codec
16:47:58.623 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:47:58.745 T:1961689088   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
16:47:58.824 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:47:58.824 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:47:58.824 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:47:58.824 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:47:58.824 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:47:58.825 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:48:00.305 T:1215296416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10215
16:48:00.305 T:1215296416   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10215
16:48:00.309 T:1215296416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218
16:48:00.309 T:1215296416   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218
16:48:03.284 T:1961689088   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218]
16:48:06.264 T:1961689088  NOTICE: VideoPlayer: Opening: https://universallivebbl-lh.akamaihd.net/i/p-2780_u-_l-_a-_c-DE_e-20388_i-4000827120171022144805_k-_q-_t-hdvideo/telekombasketball07_1@42868/master.m3u8?hdnea=exp=1508683985~acl=*~hmac=8be26713750ede94a8893a919e7a9fd751da630d349e83be1b159569104b6b7b
16:48:06.264 T:1961689088 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:48:06.513 T:1267725216  NOTICE: Creating InputStream
16:48:06.803 T:1267725216  NOTICE: Creating Demuxer
16:48:16.083 T:1267725216  NOTICE: Opening stream: 12 source: 256
16:48:16.083 T:1267725216  NOTICE: Creating video codec with codec id: 28
16:48:16.095 T:1267725216  NOTICE: Creating video thread
16:48:16.096 T:1267725216  NOTICE: Opening stream: 13 source: 256
16:48:16.096 T:1135604640  NOTICE: running thread: video_thread
16:48:16.096 T:1267725216  NOTICE: Finding audio codec for: 86018
16:48:16.098 T:1267725216  NOTICE: Creating audio thread
16:48:16.099 T:1127216032  NOTICE: running thread: CVideoPlayerAudio::Process()
16:48:16.104 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:48:16.104 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:48:16.104 T:1267725216  NOTICE: CVideoPlayer::OnExit()
16:48:16.104 T:1267725216  NOTICE: Closing stream player 1
16:48:16.104 T:1267725216  NOTICE: Waiting for audio thread to exit
16:48:16.109 T:1127216032  NOTICE: thread end: CVideoPlayerAudio::OnExit()
16:48:16.109 T:1267725216  NOTICE: Closing audio device
16:48:16.110 T:1267725216  NOTICE: Deleting audio codec
16:48:16.110 T:1267725216  NOTICE: Closing stream player 2
16:48:16.110 T:1267725216  NOTICE: waiting for video thread to exit
16:48:16.119 T:1135604640  NOTICE: thread end: video_thread
16:48:16.119 T:1267725216  NOTICE: deleting video codec
16:48:16.149 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:48:16.150 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:48:16.150 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:48:16.150 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:48:20.494 T:1961689088   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218]
16:48:23.100 T:1961689088  NOTICE: VideoPlayer: Opening: https://universallivebbl-lh.akamaihd.net/i/p-2780_u-_l-_a-_c-DE_e-20388_i-7263757020171022144822_k-_q-_t-hdvideo/telekombasketball07_1@42868/master.m3u8?hdnea=exp=1508684002~acl=*~hmac=5d649f947631a5b4166b087b046244be5c250ac29a0fa7c30b4220f48467ff03
16:48:23.100 T:1961689088 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
16:48:23.343 T:1303016352  NOTICE: Creating InputStream
16:48:23.368 T:1303016352  NOTICE: Creating Demuxer
16:48:32.012 T:1303016352  NOTICE: Opening stream: 12 source: 256
16:48:32.013 T:1303016352  NOTICE: Creating video codec with codec id: 28
16:48:32.024 T:1303016352  NOTICE: Creating video thread
16:48:32.025 T:1303016352  NOTICE: Opening stream: 13 source: 256
16:48:32.025 T:1303016352  NOTICE: Finding audio codec for: 86018
16:48:32.025 T:1267725216  NOTICE: running thread: video_thread
16:48:32.028 T:1303016352  NOTICE: Creating audio thread
16:48:32.028 T:1127216032  NOTICE: running thread: CVideoPlayerAudio::Process()
16:48:32.042 T:1127216032  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
16:48:33.114 T:1267725216 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
16:49:37.814 T:1961689088 WARNING: Previous line repeats 3 times.
16:49:37.814 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:49:37.815 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:49:37.817 T:1303016352  NOTICE: CVideoPlayer::OnExit()
16:49:37.817 T:1303016352  NOTICE: Closing stream player 1
16:49:37.817 T:1303016352  NOTICE: Waiting for audio thread to exit
16:49:37.861 T:1127216032  NOTICE: thread end: CVideoPlayerAudio::OnExit()
16:49:37.861 T:1303016352  NOTICE: Closing audio device
16:49:37.914 T:1303016352  NOTICE: Deleting audio codec
16:49:37.914 T:1303016352  NOTICE: Closing stream player 2
16:49:37.914 T:1303016352  NOTICE: waiting for video thread to exit
16:49:37.964 T:1267725216  NOTICE: thread end: video_thread
16:49:37.966 T:1303016352  NOTICE: deleting video codec
16:49:37.990 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:49:38.106 T:1961689088   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
16:49:38.180 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:49:38.181 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:49:38.181 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:49:38.181 T:1961689088  NOTICE: CVideoPlayer::CloseFile()
16:49:38.181 T:1961689088  NOTICE: VideoPlayer: waiting for threads to exit
16:49:38.181 T:1961689088  NOTICE: VideoPlayer: finished waiting
16:49:38.755 T:1135604640 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10215
16:49:38.755 T:1135604640   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10215
16:49:38.758 T:1135604640 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218
16:49:38.758 T:1135604640   ERROR: InputStream: Error opening, plugin://plugin.video.telekomsport/?mode=event&event=%2Fevent%2F10218
16:49:44.229 T:1798304672   ERROR: OnTvStandby - Unexpected [standby_pc_on_tv_standby] setting value

**Comment by hubsif** [comment]
> Ein Stream wird dann nicht abgespielt, wenn ein Stream bereits läuft, dieser beendet wird un ein neuer gestartet wird.

Wie genau meinst du das? Am gleichen Kodi startest du einen Stream, während im Hintergrund noch ein anderer läuft?

Die Logfiles sagen scheinbar leider nicht viel. Aber du hast logs von Windows und LibreELEC gepostet. Meinst du dann evtl. dass du auf zwei geräten gleichzeitig schauen möchtest?

**Comment by MRLB** [comment]
Bei mir ist es so. Wenn ich einen neuen Stream starte, während ein anderer im Hintergrund noch läuft, dann öffnet er nicht und bringt eine Fehlermeldung. Erst beim zweiten klicken (während der andere Stream im Hintergrund schon geschlossen wurde), ging's dann problemlos.

**Comment by BugM-eNot** [comment]
Guten Abend und zuallererst ein herzliches Danke @hubsif für Deine Arbeit hier - wenn schon von offizieller Seite keine anständige Möglichkeit geboten wird, die Spiele unter Android zu sehen, auf Dich und die Qualität Deiner Erweiterung ist wenigstens Verlass :)

Aber genug des Schleimes, mich plagt ebenfalls ein hier bereits erwähnter Fehler. Ich habe zwar leider keine Logs, hoffe aber, meine Ausführungen helfen bei einer eventuellen Analyse trotzdem etwas:

Bei bestimmten Basketball Live-Spielen bekomme ich sporadisch ein Fenster mit einer Fehlermeldung ("Playback failed: One or more items failed to play. [...]"), welches dann - obwohl der Live-Stream trotzdem startet - in der Mitte des Bildschirms stehen bleibt und nur mit "OK" bestätigt werden kann. Eine solche Bestätigung wiederum führt allerdings dazu, dass der Live-Stream beendet wird und Kodi wieder in die Übersicht der Spiele springt. 

Dies tritt wie gesagt sporadisch auf, bei einem zweiten oder dritten Versuch kann es sein, dass die Fehlermeldung ausbleibt. Mit einem mehrfachen Start eines Streams bzw. Start eines zweiten während ein erster noch läuft, hat der Fehler meines Erachtens nichts zu tun, da er auch auftritt, wenn nur ein einziger Stream direkt nach Öffnen des TS Add-Ons (einmalig) gestartet wird.

War das jetzt halbwegs verständlich? ;)

tl;dr: Ein hässliches, schwarzes Fehlerfenster, welches sich nicht schließen lässt, ohne dass der Stream beendet wird, blockiert sporadisch und nicht reproduzierbar die Mitte meines Bildschirms bei Telekom Basketball Live-Streams. Hilfe.

**Comment by hubsif** [comment]
Hallo @BugM-eNot ,
Sorry für die späte Antwort. Ich denke ich hab dein Problem dank der ausführlichen Beschreibung verstanden und werde mal nachforschen sobal ich Zeit habe.

**Comment by jwobbevilla** [comment]
Ich habe ebenfalls den Fehler, dass das Pop-up in der Mitte des Bildscheins verharrt. Ein schließen des Popups führt zum Abbruch des streams. Der Stream läuft dabei im Hintergrund einwandfrei. 
Passiert beim mir beim Eishockey ( was anderes schaue ich nicht).

Mein Vorgehen:
Beim erstmaligen klicken auf einen Livestream passiert nichts. Beim zweiten Mal öffnet sich der Stream und gleichzeitig ein Pop-up "Mindestens eine Datei konnte nicht abgespielt werden". Das ist die Fehlermeldung für das erste scheitern. Das Pop-up lässt sich aber dann nicht ohne Beendigung des streams schließen. 

Gibt's hierzu mittlerweile eine Lösung ?

**Comment by hubsif** [comment]
Nachdem dieses Issue schon eine Weile alt ist, bei mir nicht mehr aufgetreten ist und möglicherweise durch v1.2.2 indirekt behoben wurde, schließe ich dieses Issue mal.
Falls der Fehler nochmal auftritt, bitte wieder öffnen.
