### ISSUE TITLE
Eiskockey DEL - Streams können nicht abgespielt werden

### ISSUE THREAD

**Issue by egolus** [hubsif/kodi-telekomsport#9]
Sowohl Gamereports, als auch Wiederholungen können nicht abgespielt werden.

im Log sehe ich folgenden Fehler:

    17:53:09.516 T:140022138661056 WARNING: Playlist Player: ListItem type must be audio or video, use ListItem::setInfo to specify!

**Comment by hubsif** [comment]
Hi,

Die Warning, die du gepostet hast, sollte das Abspielen nicht beeinflussen. Was sagt den das Log noch? Denn bei mir funktioniert es bei BBL, ich denke DEL sollte dann eigentlich auch funktionieren.

**Comment by egolus** [comment]
Ich habe mir das Problem inzwischen nochmal genauer angeschaut. Das Problem tritt nicht nur in DEL auf, sondern überall. Livestreams funktionieren, aber die Einträge `Gamereport` und `Wiederholung` zu einem vergangenen Spiel funktionieren nicht.
Für diese Einträge wird das Addon anscheinend gar nicht aufgerufen.

z.B. der Eintrag `MHP RIESEN Ludwigsburg - Brose Bamberg` in Basketball - Easy Credit BBL > Woche 4 löst einen addon-Aufruf aus und `args` hat folgenden Wert: `{'event': '/event/10212', 'mode': 'event'}`

für den Eintrag `Gamereport` sehe ich im Debug-Log nur 

    OnPlayMedia plugin://plugin.video.telekomsport/?isLivestream=False&isPay=False&mode=video&videoid=34053

aber keinen Aufruf des Addons. Ich hätte einen Aufruf mit `mode: video` erwartet
